### ISSUE TITLE
Undefined subroutine

### ISSUE THREAD

**Issue by nkh** [perlancar/perl-Text-ANSI-Util#1]
$output .= ta_wrap
                (
                $element_description,
                $columns,
                {
                        flindent => $tree_header,
                        slindent => $tree_subsequent_header,
                }
                ) ;

Undefined subroutine &Text::WideChar::Util::_get_indent_width called at /home/nadim/perl5/lib/perl5/Text/ANSI/BaseUtil.pm line 272.

**Comment by perlancar** [comment]
Sorry for the late response. I didn't see the notification.

Fixed in commit 8202aea.
