### ISSUE TITLE
warning from synopsis example

### ISSUE THREAD

**Issue by nkh** [perlancar/perl-Text-ANSI-Util#2]
say ta_pad("foo\nbarbaz\n", 10, "center", "."); # => "...foo....\n..barbaz..\n" ;

output:
Negative repeat count does nothing at /home/nadim/perl5/lib/perl5/Text/ANSI/BaseUtil.pm line 515.
foo
barbaz

**Comment by perlancar** [comment]
Sorry for the very late response. I didn't see the notification for this issue.

Fixed in commit 2b46002.
