### ISSUE TITLE
Text::ANSI::Util not in modules index list

### ISSUE THREAD

**Issue by gryphonshafer** [perlancar/perl-Text-ANSI-Util#4]
It seems Text::ANSI::Util is not in the modules index list on CPAN/MetaCPAN:

- https://metacpan.org/search?q=Text%3A%3AANSI%3A%3AUtil
- https://cpan.metacpan.org/modules/02packages.details.txt

**Comment by perlancar** [comment]
PAUSE index gets messed up from time to time. I issued a reindex for Tex-ANSI-Util-* files in my PAUSE account about an hour ago. The module now shows up.
